version: '2.2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html/libraryapp:rw
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:rw
    command: nginx
    environment:
      - ENVIRONMENT=DEVELOPMENT
    restart: unless-stopped
    networks:
      - library_net
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html/libraryapp:rw
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:rw
      - ${DATA_FOLDER:-./data}/images:/var/www/html/libraryapp/public/images:rw
    environment:
      - ENVIRONMENT=DEVELOPMENT
    networks:
      - library_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=http"
      - "traefik.http.routers.backend.rule=Host(`reading-room.me`)"
      - "traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.backend.middlewares=wiki-https-redirect"
      - "traefik.http.routers.backend-secure.entrypoints=https"
      - "traefik.http.routers.backend-secure.rule=Host(`reading-room.me`)"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=http"
      - "traefik.http.routers.backend-secure.service=wiki"
      - "traefik.http.services.backend.loadbalancer.server.port=8888"
      - "traefik.docker.network=proxy"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=library
    ports:
      - ${DB_BIND_ADDRESS:-127.0.0.1}:${DB_PORT-3306}:3306
    volumes:
      - ${DATA_FOLDER:-./data}/mysql/data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - library_net
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"


  traefik:
    image: traefik:v2.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - library_net
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`monitor.domain.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:secret_password"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`monitor.domain.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  library_net:
    name: library_net
    driver: bridge
    internal: false
    external: true
